#!/bin/bash

# Complex test for minion. Test for 3 blocks with random data. 
if [ ! -n "$2" ]; then
    echo "Please enter your minion IP and Port number.(for example: 127.0.0.1 12345)" 
    echo "You should run your minion before running this script.."
else
    # directory for the test blocks
    mkdir -p blocks
    # generate 3 random blocks for the test
    ./cblock_files blocks 3 1 
    # Generate write request
    ./write_req 0 blocks/block0 "$1" "$2"
    # Generate write request
    ./write_req 1 blocks/block1 "$1" "$2"
    # Generate read request
    ./read_req 1 blocks/block1 "$1" "$2"
    # Generate write request
    ./write_req 2 blocks/block2 "$1" "$2"
    # Generate read request
    ./read_req 0 blocks/block0 "$1" "$2"
    # Generate read request
    ./read_req 2 blocks/block2 "$1" "$2"
fi